version: '3.8'

services:
  standup_companion_database:
    container_name: standup_companion_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  standup_companion_php:
    container_name: standup_companion_php
    build:
      context: ./Docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - standup_companion_database

  standup_companion_nginx:
    container_name: standup_companion_nginx
    image: nginx:stable-alpine
    ports:
      - '8889:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - standup_companion_php
      - standup_companion_database